version: '3.8'

services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
    working_dir: /app
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: gradle test --tests "*DirectMigration*" --no-daemon --info
    depends_on:
      - postgres-test

  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data: